name: go-http

on: [push]

jobs:
  go-http:
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ./go+http
    steps:
      - uses: actions/checkout@v2
        name: Checkout do projeto
      
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./go+http
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frameworks-performance-go-http:latest
      
  test-go-http:
    runs-on: ubuntu-latest
    needs: [go-http]

    steps:
      - name: Running Application
        run: docker run -d --net=host -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/frameworks-performance-go-http:latest 
      
      - name: Waiting 10 seconds
        run: sleep 10
      
      - name: Running Performance Test (-C 100)
        run: docker run --net=host -i alpine/bombardier -c 100 -n 50000 -l localhost:8080/hello -o json | tee  >(tail -n 1 > result.json)     

      

  
            
      

      